name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Use file '...'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you running?
      options:
        - Python 3.10
        - Python 3.11
        - Python 3.12
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (Other)
        - Other (please specify in additional context)
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error output
      description: If applicable, copy and paste the full error message or traceback
      render: shell

  - type: textarea
    id: sample-file
    attributes:
      label: Sample file
      description: If the issue involves a specific file, please describe the file or provide a minimal example that reproduces the issue

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here